sudo: required
dist: xenial

language: cpp

compiler:
  - gcc

jobs:
  include:
    - stage: deps
      script: ./mcrouter/scripts/install_ubuntu_16.04_deps.sh "$(pwd)"/mcrouter-install
    - stage: mcrouter
      script: ./mcrouter/scripts/install_ubuntu_16.04_mcrouter.sh "$(pwd)"/mcrouter-install

notifications:
  email:
    - lukeye@fb.com
